using System.IO;
using UnityEditor;
using UnityEngine;

namespace CHG.Editor.ScriptTemplator
{
    public static class TemplateBaker
    {
        public static void CreateTemplatorScript(string path, TextAsset[] assets)
        {
            string filename = "BakedScriptTemplates.cs";
            
            string fullPath = Path.Combine(path, filename);

            string content = "///Auto-Generated By TemplateBaker///\n\n\n";
            content += "using UnityEngine;\n";
            content += "using UnityEditor;\n";
            content += "namespace CHG.Editor.ScriptTemplates.Generated\n";
            content += "{";
            content += "\tpublic static class BakedScriptTemplates\n";
            content += "\t{\n";

            string assetPath;
            for(int i = 0; i < assets.Length; ++i)
            {
                assetPath = AssetDatabase.GetAssetPath(assets[i]);
                content += $"\t\t[MenuItem(\"Assets/Create/Create Script By Templates/{assets[i].name}\", priority = 80)]\n";
                content += $"\t\tstatic void CreateScript{i}()\n";
                content += "\t\t{\n";
                content += $"\t\t\tProjectWindowUtil.CreateScriptAssetFromTemplateFile(\"{assetPath}\",\"New{assets[i].name}.cs\");\n";
                content += "\t\t}\n";
            }
            content += "\t}\n";
            content += "}";
            File.WriteAllText(fullPath, content);
            AssetDatabase.ImportAsset(fullPath);
        }
    }
}